version: '3.8'
services:
  tennis-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ./database/.env
    volumes:
         # copy the sql script to create tables
          - ./database/tennis.sql:/docker-entrypoint-initdb.d/tennis.sql
          - ./postgres-data:/var/lib/postgresql/data


  tennis-api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - .:/api/src
    command: npm run start
    ports:
      - 3012:3012
    env_file: ./api/.env
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      PGHOST: tennis-db
    depends_on: 
      - tennis-db
  
  tennis-app:
    restart: always
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    env_file: ./app/.env
    command: npm start
    depends_on: 
      - tennis-api
